package dm.vodafone.com;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2014-11-13T23:44:04.798+04:00
 * Generated source version: 2.7.9
 * 
 */
@WebService(targetNamespace = "com.vodafone.dm", name = "DecisionControllerWS")
@XmlSeeAlso({ObjectFactory.class, dm.com.vodafone.dm.ws.ObjectFactory.class, dm.com.vodafone.dm.is.ObjectFactory.class, dm.com.chordiant.dm.ra.ObjectFactory.class})
public interface DecisionControllerWS {

    @WebResult(name = "DecisionResult", targetNamespace = "com.vodafone.dm")
    @RequestWrapper(localName = "getOffers", targetNamespace = "com.vodafone.dm", className = "dm.vodafone.com.GetOffers")
    @WebMethod
    @ResponseWrapper(localName = "getOffersResponse", targetNamespace = "com.vodafone.dm", className = "dm.vodafone.com.GetOffersResponse")
    public dm.com.vodafone.dm.ws.ProductArray getOffers(
        @WebParam(name = "request", targetNamespace = "com.vodafone.dm")
        dm.com.vodafone.dm.ws.Request request
    );

    @RequestWrapper(localName = "setResponse", targetNamespace = "com.vodafone.dm", className = "dm.vodafone.com.SetResponse")
    @WebMethod
    @ResponseWrapper(localName = "setResponseResponse", targetNamespace = "com.vodafone.dm", className = "dm.vodafone.com.SetResponseResponse")
    public void setResponse(
        @WebParam(name = "conversationID", targetNamespace = "com.vodafone.dm")
        java.lang.String conversationID,
        @WebParam(name = "MSISDN", targetNamespace = "com.vodafone.dm")
        java.lang.String msisdn,
        @WebParam(name = "propositionArray", targetNamespace = "com.vodafone.dm")
        dm.com.vodafone.dm.ws.PropositionArray propositionArray,
        @WebParam(name = "type", targetNamespace = "com.vodafone.dm")
        java.lang.String type,
        @WebParam(name = "sourceSystem", targetNamespace = "com.vodafone.dm")
        java.lang.String sourceSystem
    );

    @RequestWrapper(localName = "reload", targetNamespace = "com.vodafone.dm", className = "dm.vodafone.com.Reload")
    @WebMethod
    @ResponseWrapper(localName = "reloadResponse", targetNamespace = "com.vodafone.dm", className = "dm.vodafone.com.ReloadResponse")
    public void reload();
}
